### ISSUE TITLE
Site is detected as a deceptive site lol

### ISSUE THREAD

**Issue by OutsFab** [ravisharma011/RSPhisher#1]
![image](https://user-images.githubusercontent.com/79458163/144357432-3ab82545-100b-4073-a0f9-f08ad33e0cdd.png)
lmao fix this

**Comment by ravisharma011** [comment]
> ![image](https://user-images.githubusercontent.com/79458163/144357432-3ab82545-100b-4073-a0f9-f08ad33e0cdd.png) lmao fix this

I understand your problem but ngrok websites are illegal but you can still open it by clicking on details and then the website is given at the bottom.
